CREATE TABLE `documentos` (
  `ID_DOCUMENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_DOCUMENTO_TIPO` INT NOT NULL,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_DOCUMENTO`)
  CONSTRAINT `DOCUMENTOS_TIPO_ID_DOCUMENTO_TIPO` FOREIGN KEY (`ID_DOCUMENTO_TIPO`) REFERENCES `documentos_tipo` (`ID_DOCUMENTO_TIPO`) ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARSET = utf8;


CREATE TABLE `documentos_personas` (
  `ID_DOCUMENTO_PERSONA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_DOCUMENTO` INT(11) NOT NULL,
  `ID_PERSONA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_DOCUMENTO_PERSONA`),
  CONSTRAINT `DOCUMENTOS_PERSONAS_ID_PERSONA` FOREIGN KEY (`ID_PERSONA`) REFERENCES `personas` (`ID_PERSONA`) ON UPDATE NO ACTION,
  CONSTRAINT `DOCUMENTOS_PERSONAS_ID_DOCUMENTO` FOREIGN KEY (`ID_DOCUMENTO`) REFERENCES `documentos` (`ID_DOCUMENTO`) ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARSET = utf8;