CREATE TABLE `invensoft`.`informaciones_laborales` (
  `id_informacion_laboral` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NULL,
  `id_cargo` INT(11) NULL,
  PRIMARY KEY (`id_informacion_laboral`),
  KEY `INFORMACION_LABORAL_UNQ` (`ID_PERSONA`, `ID_CARGO`),
  CONSTRAINT `PERSONAS_ID_PERSONA` FOREIGN KEY (`ID_PERSONA`) REFERENCES `personas` (`ID_PERSONA`) ON UPDATE NO ACTION,
  CONSTRAINT `CARGOS_ID_CARGO` FOREIGN KEY (`ID_CARGO`) REFERENCES `cargos` (`ID_CARGO`) ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

